var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
var webpack=require("webpack"),path=require("path"),fs=require("fs"),pug=require("pug"),CopyWebpackPlugin=require("copy-webpack-plugin"),WebpackNotifierPlugin=require("webpack-notifier"),glob=require("glob"),wilokePlugin=require("./webpack.config/wilokePlugin.js"),createFileJsPlugin=require("./webpack.config/createFileJsPlugin.js"),mkdirp=require("mkdirp"),activate=process.env.activate?process.env.activate:"_blank",isDev="dev"===process.env.NODE_ENV,appConfig=require("./app.config.js"),entryPath=
appConfig.folders.path+"/"+appConfig.folders.content+"/"+activate+"/"+appConfig.entry.path,outputPath=appConfig.folders.path+"/"+appConfig.folders.content+"/"+activate+"/"+appConfig.output.path,rulesStyle=require("./webpack.config/style.js"),loaderoptionsPlugin=require("./webpack.config/loaderoptionsPlugin.js"),config_template=require("./"+appConfig.folders.path+"/"+appConfig.folders.content+"/"+activate+"/config.js");function encode(a){return(new Buffer(a)).toString("base64")}
function decode(a){return(new Buffer(a+"\x3d","base64")).toString("ascii")}var app=require("express")(),bodyParser=require("body-parser"),router=require("./webpack.config/router.js");app.use(bodyParser.json());app.use(bodyParser.urlencoded({extended:!0}));var patternActivateDir=[],pushPattern=function(a,b){var d=fs.readdirSync(b);d=$jscomp.makeIterator(d);for(var c=d.next();!c.done;c=d.next())c=encode(b+"/"+c.value),a.push(c)};pushPattern(patternActivateDir,entryPath+"/_pattern");
pushPattern(patternActivateDir,appConfig.folders.path+"/"+appConfig.folders.core+"/_pattern");var entry={bundle:["webpack-hot-middleware/client/",path.resolve(__dirname,"./"+appConfig.folders.path+"/"+appConfig.folders.content+"/"+activate+"/"+appConfig.entry.filename),path.resolve(__dirname,"./"+entryPath+"/"+appConfig.entry.css)]},stats={assets:!1,colors:!0,version:!1,hash:!1,timings:!0,chunks:!1,chunkModules:!1,children:!1};
module.exports={stats:stats,entry:entry,output:{path:path.resolve(__dirname,"./"+entryPath),filename:"bundle.js"},devtool:"inline-source-map",resolve:{modules:["./","node_modules",appConfig.folders.path+"/"+appConfig.folders.content+"/"+activate,entryPath+"/",entryPath+"/_pattern"],extensions:".js .json .css .scss .html .pug .txt".split(" "),alias:{imagesLoaded:"imagesloaded",flickity:"flickity",masonry:"masonry-layout",isotope:"isotope-layout","eventEmitter/EventEmitter":"wolfy87-eventemitter/EventEmitter",
"get-style-property":"desandro-get-style-property","matches-selector":"desandro-matches-selector",classie:"desandro-classie"}},module:{rules:[rulesStyle,{test:/\.exec\.js$/,use:["script-loader"]},{enforce:"pre",test:/\.js/,loader:"import-glob-loader"},{enforce:"pre",test:/\.scss/,loader:"import-glob-loader"}]},plugins:[new wilokePlugin({authorTree:patternActivateDir,appConfig:appConfig,beauty:"\t",styles:{updateClass:!1}}),new createFileJsPlugin,loaderoptionsPlugin,new WebpackNotifierPlugin,new webpack.HotModuleReplacementPlugin,
new webpack.NamedModulesPlugin]};function rmdir(a){for(var b=fs.readdirSync(a),d=0;d<b.length;d++){var c=path.join(a,b[d]),e=fs.statSync(c);"."!=c&&".."!=c&&(e.isDirectory()?rmdir(c):fs.unlinkSync(c))}fs.rmdirSync(a)}function remove_duplicates(a){for(var b={},d=[],c=0;c<a.length;c++)b[a[c]]=!0;for(var e in b)d.push(e);return d}
function contentAppJs(){return"\nfunction requireAll(r) {\n\tr.keys().forEach(r);\n}\n/**\n* Require file app style\n*/\n\n// Base core\nrequireAll(require.context('"+appConfig.folders.path+"/"+appConfig.folders.core+"/styles/base/', true, /.(scss|sass|css)$/));\n\n// Base template\nrequireAll(require.context('./base/', true, /.(scss|sass|css)$/));\n\n// Template Pattern\nrequireAll(require.context('_pattern/', true, /.(scss|sass|css)$/));\n\n// Core Pattern\nrequireAll(require.context('"+appConfig.folders.path+
"/"+appConfig.folders.core+"/_pattern/', true, /.(scss|sass|css)$/));\n\n// Template\nrequireAll(require.context('./', true, /.(scss|sass|css)$/));\n"}fs.writeFileSync(entryPath+"/"+appConfig.entry.css,contentAppJs());var MergeIntoSingleFilePlugin=require("webpack-merge-and-include-globally"),config_template_appJs=[appConfig.folders.path+"/"+appConfig.folders.core+"/js/appFirst.js"],config_template_appJs_core=[];
for(i=0;i<=config_template.appJs.length&&i!=config_template.appJs.length;i++)config_template_appJs_core.push(appConfig.folders.path+"/"+appConfig.folders.core+"/js/"+config_template.appJs[i]);var jsPatternArr=[appConfig.folders.docs+"/fileJavascriptJoin.js",appConfig.folders.path+"/"+appConfig.folders.core+"/js/appLast.js"],config_template_appJs_newtemplate=[appConfig.folders.path+"/"+appConfig.folders.content+"/"+activate+"/"+appConfig.entry.path+"/"+appConfig.entry.js];
config_template_appJs.push.apply(config_template_appJs,config_template_appJs_core);config_template_appJs.push.apply(config_template_appJs,config_template_appJs_newtemplate);config_template_appJs.push.apply(config_template_appJs,jsPatternArr);var outputJs=appConfig.output.js,merge_appJs={};merge_appJs[outputJs]=config_template_appJs;var merge_all=merge_appJs;module.exports.plugins.push(new MergeIntoSingleFilePlugin({files:merge_all}));
var deleteFolderRecursive=function(a){fs.existsSync(a)&&(fs.readdirSync(a).forEach(function(b,d){b=a+"/"+b;fs.lstatSync(b).isDirectory()?deleteFolderRecursive(b):fs.unlinkSync(b)}),fs.rmdirSync(a))},contentMain="\nfunction requireAll(r) {\n\tr.keys().forEach(r);\n}\n/**\n * Require all page pug, html\n */\n\nrequireAll(require.context('./app/', false, /.(pug|html)$/));\n";isDev&&(contentMain="\nfunction requireAll(r) {\n\tr.keys().forEach(r);\n}\n/**\n * Require all page pug, html\n */\n\nrequireAll(require.context('./app/', false, /.(html)$/));\n");
fs.writeFileSync(path.resolve(__dirname,"./"+appConfig.folders.path+"/"+appConfig.folders.content+"/"+activate+"/main.js"),contentMain);var indexTemplateContents="\nextends pug/layout\n\n//- Config\nblock config\n\t-\n\t\tconfig.title \x3d '"+activate+" elements'\n\t\tconfig.bodyClass \x3d 'pattern-core-app'\n\ninclude /../"+appConfig.folders.docs+"/docs\n";fs.writeFileSync(path.resolve(__dirname,"./",entryPath+"/index.pug"),indexTemplateContents);
var docsFileContent=fs.readFileSync(appConfig.folders.docs+"/docs.pug","utf-8"),newDocsFileContent=docsFileContent.replace(/include.*docs-includes\.pug/g,"include /"+appConfig.folders.content+"/"+activate+"/"+appConfig.entry.path+"/pug/docs-includes/docs-includes.pug");fs.writeFileSync(appConfig.folders.docs+"/docs.pug",newDocsFileContent);