var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.assign="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)$jscomp.owns(d,e)&&(a[e]=d[e])}return a};$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Object.assign",function(a){return a||$jscomp.assign},"es6","es3");
var express=require("express"),glob=require("glob"),pug=require("pug"),watch=require("node-watch"),activate=process.env.activate||"_blank",appConfig=require("../app.config.js"),entryPath=appConfig.folders.path+"/"+appConfig.folders.content+"/"+activate+"/"+appConfig.entry.path,fs=require("fs"),pages=glob.sync(entryPath+"/*.pug"),options={pretty:!1,exports:!1,debug:!1,compileDebug:!1,cache:!1,require:require,__dirname:__dirname,__filename:__filename},special="\nextends /"+appConfig.folders.content+
"/"+activate+"/"+appConfig.entry.path+"/pug/layout\n\n//- Config\nblock config\n\t-\n\t\tconfig.title \x3d 'Special'\n\t\tconfig.bodyClass \x3d 'body-special-page'\n\n//- afterLink\nblock afterLink\n\t\n//- Header\nblock header\n\t\n//- Footer\nblock footer\n\t\n//- Content\nblock content\n\th1 Special page\n";
module.exports=function(){var a=express.Router();a.get("/",function(a,b){return b.render("index",options)});var b=pug.render(special,Object.assign(options,{basedir:"./"+appConfig.folders.path}));a.get("/special",function(a,c){return c.send(b)});var c=function(){pages=glob.sync(entryPath+"/*.pug",{ignore:"DS_Store"});for(var b={},c=$jscomp.makeIterator(pages),f=c.next();!f.done;b={_val:b._val},f=c.next())b._val=f.value.replace(/.*(\\|\/)/g,"").replace(/\.pug/g,""),a.get("/"+b._val+".html",function(a){return function(b,
c){return c.render(a._val,options)}}(b))};c();watch(entryPath,{recursive:!0},function(a,b){return c()});return a}();