var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var e=b.length;for(c=c||0;c<e;c++)if(b[c]==a||Object.is(b[c],a))return!0;return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,c||0)}},"es6","es3");
var fs=require("fs"),path=require("path"),pug=require("pug"),glob=require("glob"),chokidar=require("chokidar"),watch=require("node-watch"),express=require("express"),webpack=require("webpack"),webpackDevMiddleware=require("webpack-dev-middleware"),webpackHotMiddleware=require("webpack-hot-middleware"),config=require("../webpack.config.js"),appConfig=require("../app.config.js"),activate=process.env.activate||"_blank",outputPath=appConfig.folders.path+"/"+appConfig.folders.content+"/"+activate+"/"+
appConfig.output.path,entryPath=appConfig.folders.path+"/"+appConfig.folders.content+"/"+activate+"/"+appConfig.entry.path,isProd="production"===process.env.NODE_ENV,isProdMinify="productionMinify"===process.env.NODE_ENV,isDev="dev"===process.env.NODE_ENV,app=express(),bodyParser=require("body-parser"),router=require("./router.js");app.use(bodyParser.json());app.use(bodyParser.urlencoded({extended:!0}));
var compiler=webpack(config),devMiddleware=webpackDevMiddleware(compiler,{inline:!0,compress:!0,hotOnly:isDev?!0:!1,stats:config.stats,open:!0}),hotMiddleware=webpackHotMiddleware(compiler,{log:console.log,path:"/__webpack_hmr",heartbeat:4E3});app.use(devMiddleware);app.use(hotMiddleware);var server=require("http").Server(app);
isDev&&(app.set("views",path.resolve(__dirname,"../"+entryPath)),app.locals.basedir=path.resolve(__dirname,"../"+appConfig.folders.path),app.set("view engine","pug"),app.use(express.static((isDev?entryPath:outputPath)+"/")),app.use(express.static(path.resolve(__dirname,"../"))),app.use("/",router));
var log=function(a){return console.log(a)},ip=require("ip"),PORT=8888,logUrl="\n-------------------------------------------------\n\nLocal:\u001b[36m http://localhost:"+PORT+" \u001b[0m\n\nExternal:\u001b[36m http://"+ip.address()+":"+PORT+" \u001b[0m\n\nTemplate activate:\u001b[36m "+activate+" \u001b[0m\n\n-------------------------------------------------\n";server.listen(PORT,function(){return log(logUrl)});
var pugOptions={pretty:!1,exports:!1,debug:!1,compileDebug:!1,cache:!1,basedir:"./"+appConfig.folders.path,require:require,__dirname:__dirname,__filename:__filename},remove_duplicates=function(a){for(var b={},c=[],d=0,e=a.length;d<e;d++)b[a[d]]=!0;for(var f in b)c.push(f);return c};
if(isDev){var io=require("socket.io")(server);compiler.plugin("emit",function(a,b){var c=a.assets[appConfig.output.js].source(),d=fs.readFileSync(path.resolve(__dirname,"./socket-io-client.js"),"utf-8");a.assets["socket-io-client.js"]={source:function(){return d},size:function(){return d.length}};a.assets["hmr-javascript.js"]={source:function(){return c},size:function(){return c.length}};b()});var arrCheckPrev=[],arrCheckCurr=[];compiler.plugin("done",function(a){a=$jscomp.makeIterator(a.compilation.fileDependencies);
for(var b=a.next();!b.done;b=a.next())b=b.value,-1!==b.indexOf("_pattern")&&arrCheckPrev.push(b)});compiler.plugin("emit",function(a,b){a=$jscomp.makeIterator(a.fileDependencies);for(var c=a.next();!c.done;c=a.next())c=c.value,-1!==c.indexOf("_pattern")&&arrCheckCurr.push(c);remove_duplicates(arrCheckPrev).length<remove_duplicates(arrCheckCurr).length&&io.emit("createCompReload","");b()});compiler.plugin("after-emit",function(a,b){var c=a.assets["hmr-javascript.js"].source(),d=setInterval(function(){return io.emit("script",
'\x3cscript type\x3d"text/javascript" class\x3d"script-app-hmr" async\x3d"false"\x3e'+c+"\x3c/script\x3e")},100);setTimeout(function(){return clearInterval(d)},200);io.emit("changeHtml","");b()});var HmrIndex=function(a,b){if(-1!==a.indexOf("_pattern")){var c=path.dirname(a)+"/demo.pug";setTimeout(function(){var a="",b=[];try{a=pug.renderFile(entryPath+"/index.pug",pugOptions),b=b.concat(a.match(/<a.*data-dir.*demo\.pug.*([\s\S]*?)<\/code><\/pre>/g))}catch(f){log("\u001b[31m"+f.message+"\u001b[0m"),
b.push('\x3cdiv class\x3d"wil-text-content-core--demo"\x3e\x3cpre style\x3d"color: #000"\x3e'+f.message+"\x3c/pre\x3e\x3c/div\x3e\x3cpre\x3e\x3ccode\x3e\x3c/code\x3e\x3c/pre\x3e")}io.emit("htmlIndexDOM",{dir:c.replace(/\\/g,"/").match(new RegExp(appConfig.folders.path+".*","g"))[0],patternArr:b})},b)}},HmrPages=function(a){var b="";try{b=pug.renderFile(a,pugOptions),null!==b.match(/<div.*id="root".*([\s\S]*?)div\sclass="start-script-flag"/g)&&(b=b.match(/<div.*id="root".*([\s\S]*?)div\sclass="start-script-flag"/g).join(""),
b=b.replace('\x3cdiv class\x3d"start-script-flag"',""))}catch(c){log("\u001b[31m"+c.message+"\u001b[0m"),b='\x3cdiv id\x3d"root"\x3e\x3cpre style\x3d"color: #000;padding:0 20px"\x3e'+c.message+"\x3c/pre\x3e\x3c/div\x3e"}io.emit("htmlDOM",{html:b,locationHref:a.replace(/.*(\/|\\)/g,"").replace(/\.pug/g,".html")})};compiler.plugin("invalid",function(a,b){b=glob.sync(entryPath+"/*.pug",{ignore:"DS_Store"});try{-1!==a.search(/\.scss/g)&&function(b){fs.exists(b,function(c){if(c){var d=chokidar.watch(b);
d.on("change",function(b){io.emit("reloadScssChange","");HmrIndex(a,0);d.close()})}})}(path.dirname(a)+"/cssmodule.pug"),-1!==a.search(/\.pug/g)&&(io.emit("reload",a.replace(/.*(\/|\\)/g,"").replace(/\.pug/g,".html")),HmrIndex(a,0),b.includes(a.replace(/\\/g,"/").match(new RegExp(appConfig.folders.path+".*","g"))[0])&&HmrPages(a)),-1!==a.search(/\.js/g)&&io.emit("change",""),-1===a.search(/\.pug/g)&&-1===a.search(/\.scss/g)||io.emit("noChange","")}catch(c){log(c.message)}})}
app.get("/dev",function(a,b){var c=appConfig.folders.path+"/"+appConfig.folders.content+"/"+activate+"/"+appConfig.data+"/comments/"+a.query.filename+".json",d=[];fs.existsSync(c)&&(d=JSON.parse(fs.readFileSync(c)));d.push(a.query);fs.writeFileSync(c,JSON.stringify(d));b.send("GET Ok")});
app.get("/api/add-comment",function(a,b){var c=appConfig.folders.path+"/"+appConfig.folders.content+"/"+activate+"/"+appConfig.data+"/comments/"+a.query.filename+".json",d=[],e="Create",f=new Date,h=(new Date).toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"});fs.existsSync(c)&&(d=fs.readFileSync(c),d=JSON.parse(d),e="Update");var g=JSON.parse(a.query.checkwork);a={checkwork:g[0],checkcolor:g[1],author:a.query.author,time:h+" "+f.getHours()+":"+f.getMinutes(),computername:process.env.COMPUTERNAME,
content:a.query.content,filename:a.query.filename};d.push(a);fs.writeFileSync(c,JSON.stringify(d));b.json({status:200,message:e+" Success",result:a})});
app.get("/api/get-comment",function(a,b){"undefined"!=typeof a.query.filename?(a=appConfig.folders.path+"/"+appConfig.folders.content+"/"+activate+"/"+appConfig.data+"/comments/"+a.query.filename+".json",fs.existsSync(a)?(a=fs.readFileSync(a),a=JSON.parse(a),b.json({status:200,message:"Success",result:a})):b.json({status:400,message:"File not found"})):b.json({status:400,message:"fileName does not exist"})});