var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
var webpack=require("webpack"),path=require("path"),fs=require("fs"),appConfig=require("../app.config.js"),activate=process.env.activate?process.env.activate:"_blank",entryPath=appConfig.folders.path+"/"+appConfig.folders.content+"/"+activate+"/"+appConfig.entry.path,postcssmodules=require("postcss-modules"),autoprefixer=require("autoprefixer"),isProd="production"===process.env.NODE_ENV,isProdMinify="productionMinify"===process.env.NODE_ENV,isDev="dev"===process.env.NODE_ENV,coreStyles="./"+appConfig.folders.path+
"/"+appConfig.folders.core+"/styles/abstracts",fileAbstracts=fs.readdirSync("./"+entryPath+"/"+appConfig.entry.css.split("/")[0]+"/"+appConfig.entry.scssImportInline+"/"),fileCoresStyles=fs.readdirSync(coreStyles);function importScss(a,b){var c="";b.forEach(function(b){c+='@import "'+a+"/"+b+'";'});return c}function encode(a){return(new Buffer(a)).toString("base64")}var scopedName;
scopedName="custom"==appConfig.generateScopedName?function(a,b,c){c=path.basename(b,".css").replace(/\.(scss|css|sass)/g,"");b=path.dirname(b).replace(/(.+\\_pattern\\|\\.+)|(.+\/_pattern\/|\/.+)/g,"");var d=appConfig.classModulePrefix;return"string"===typeof d[b]?d[b]+c+"__"+a:b+"_"+c+"__"+a}:appConfig.generateScopedName;
var config={test:appConfig.use.css,use:[{loader:"style-loader",options:{url:!1,sourceMap:!0}},{loader:"css-loader",options:{url:!1,sourceMap:!0}},{loader:"postcss-loader",options:{sourceMap:!0,plugins:function(a){return[postcssmodules({root:"",generateScopedName:scopedName,getJSON:function(a,c){path.basename(a,".css");a=path.dirname(a);var b=a+"/cssmodule.pug";-1===a.indexOf(appConfig.entry.css.replace(/(\/|\\).*/g,""))&&0<Object.keys(c).length&&(fs.readdir(a,function(a,c){-1===c.indexOf("cssmodule.pug")&&
fs.writeFile(b,"",function(a){if(a)throw a;})}),fs.readFile(b,"utf-8",function(a,d){if(a)throw a;"- css \x3d "+JSON.stringify(c)!==d&&fs.writeFile(b,"- css \x3d "+JSON.stringify(c),function(a){if(a)throw a;})}))}})]}}},{loader:"sass-loader",options:{sourceMap:!0,sourceMapContents:!0,data:importScss(appConfig.entry.scssImportInline,fileAbstracts)+importScss(coreStyles,fileCoresStyles),includePaths:[path.resolve(__dirname,"../"+entryPath+"/"+appConfig.entry.css.split("/")[0])]}}]};module.exports=config;