var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.assign="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)$jscomp.owns(d,e)&&(a[e]=d[e])}return a};$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Object.assign",function(a){return a||$jscomp.assign},"es6","es3");$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof e?a:new e(function(g,b){g(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(m){this.asyncThrow_(m)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(h){b.reject(h)}};e.prototype.createResolveAndReject_=
function(){function a(a){return function(g){c||(c=!0,a.call(b,g))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(h){this.reject_(h);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var f=new b;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(m){c.reject(m)}};e.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{g(a(b))}catch(n){d(n)}}:b}var g,d,f=new e(function(a,
b){g=a;d=b});this.callWhenSettled_(c(a,g),c(b,d));return f};e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function c(){switch(e.state_){case 1:a(e.result_);break;case 2:b(e.result_);break;default:throw Error("Unexpected state: "+e.state_);}}var e=this;null==this.onSettledCallbacks_?f.asyncExecute(c):this.onSettledCallbacks_.push(function(){f.asyncExecute(c)})};e.resolve=c;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(b,
e){for(var g=$jscomp.makeIterator(a),d=g.next();!d.done;d=g.next())c(d.value).callWhenSettled_(b,e)})};e.all=function(a){var b=$jscomp.makeIterator(a),g=b.next();return g.done?c([]):new e(function(a,e){function d(b){return function(c){f[b]=c;h--;0==h&&a(f)}}var f=[],h=0;do f.push(void 0),h++,c(g.value).callWhenSettled_(d(f.length-1),e),g=b.next();while(!g.done)})};return e},"es6","es3");
var fs=require("fs"),path=require("path"),glob=require("glob"),watch=require("node-watch"),chokidar=require("chokidar"),isDev="dev"===process.env.NODE_ENV,activate=process.env.activate||"_blank",rqPattern=process.env.requirePattern||"",wilokePlugin=function(a){this.includeComp={};this.includeDemo={};this.opts=Object.assign({appConfig:{},authorTree:[],beauty:"\t",styles:{updateClass:!0},cssModuleForJs:!0},a)};
wilokePlugin.prototype.pugBasic=function(){var a=this.opts;return"//- demo: true\nmixin ComponentName(args)\n"+a.beauty+"include cssmodule\n\n"+a.beauty+"+module('div', css.module, args)\n"+a.beauty+a.beauty+"- let args \x3d item\n"+a.beauty+a.beauty+"\n"+a.beauty+a.beauty+"//- code\n"+a.beauty+a.beauty+"\n"+a.beauty+a.beauty+"\n"+a.beauty+a.beauty+"\n"+a.beauty+"include cssmodule\n"};
wilokePlugin.prototype.pageBasic=function(){var a=this.opts;return"extends pug/layout\n\n//- Config\nblock config\n"+a.beauty+"-\n"+a.beauty+a.beauty+"config.title \x3d 'PageTitleBasic'\n"+a.beauty+a.beauty+"config.bodyClass \x3d ''\n\n//- afterLink\nblock afterLink\n"+a.beauty+"\n//- Header\nblock header\n"+a.beauty+"\n//- Footer\nblock footer\n"+a.beauty+"\n//- Content\nblock content\n"+a.beauty+"\n"};
wilokePlugin.prototype.jsBasic=function(a){var b=this.opts,c="";-1!==a.search(/^.*(\s+|)class/g)?c="class jsBasicPattern {\n"+b.beauty+"constructor() {\n"+b.beauty+b.beauty+"this.css \x3d replaceCssModule;\n"+b.beauty+b.beauty+"this.apply();\n"+b.beauty+"}\n"+b.beauty+"\n"+b.beauty+"apply() {\n"+b.beauty+b.beauty+"const { css } \x3d this;\n"+b.beauty+b.beauty+"\n"+b.beauty+"}\n}\nnew jsBasicPattern();\n":-1!==a.search(/^.*(\s+|)function/g)&&(c="function jsBasicPattern() {\n"+b.beauty+"const css \x3d replaceCssModule;\n"+
b.beauty+"\n}\njsBasicPattern();\n");return c};wilokePlugin.prototype.createBasicPage=function(){var a=this,b=this.opts.appConfig;watch(b.folders.path+"/"+b.folders.content+"/"+activate+"/"+b.entry.path,{recursive:!1},function(b,d){-1!==d.indexOf(".pug")&&fs.exists(d,function(b){b&&fs.readFile(d,"utf-8",function(b,c){if(b)throw b;""===c&&(b=a.pageBasic().replace(/PageTitleBasic/g,d.replace(/(.*(\\|\/))|(\.pug)/g,"")),fs.writeFile(d,b,function(a){if(a)throw a;}))})})})};
wilokePlugin.prototype.writeFilePugComp=function(a,b){var c=this;-1===b.search(/\.(js|scss|css|pug|jpg|svg|gif|png|DS_Store)/g)&&fs.exists(b,function(d){d&&fs.readdir(b,function(e,d){if(e)throw e;if(0===d.length){e=b.replace(/.*(\\|\/)/g,"");d=a.replace(/.*(\\|\/)/g,"");var g=c.pugBasic().replace(/ComponentName/g,camelCase(d+"-"+e)),f=b+"/"+e+".pug";fs.exists(f,function(a){a||fs.writeFile(f,g,function(a){if(a)throw a;})})}})})};
wilokePlugin.prototype.watchFolderComp=function(a){var b=this;fs.readdirSync(a);watch(a,{recursive:!0},function(c,d){return b.writeFilePugComp(a,d)})};wilokePlugin.prototype.filePugComp=function(a){return glob.sync(a+"/**/*.pug",{ignore:[a+"/**/cssmodule.pug",a+"/**/demo.pug",a+"/**/data.pug","DS_Store"]})};wilokePlugin.prototype.filePugCompAndData=function(a){return glob.sync(a+"/**/*.pug",{ignore:[a+"/**/cssmodule.pug",a+"/**/demo.pug","DS_Store"]})};
wilokePlugin.prototype.checkPugFile=function(a){var b=this,c={};a=$jscomp.makeIterator(this.filePugComp(a));for(var d=a.next();!d.done;c={pugFile:c.pugFile,compFolder:c.compFolder},d=a.next())c.pugFile=d.value,c.compFolder=path.dirname(c.pugFile),fs.readFile(c.pugFile,"utf-8",function(a){return function(c,d){if(c)throw c;b.writeCssModuleFile(a.pugFile,a.compFolder,d);b.writeScssFile(a.pugFile,a.compFolder,d);b.writeFileDemo(a.pugFile,a.compFolder,d)}}(c))};
wilokePlugin.prototype.writeCssModuleFile=function(a,b,c){-1!==c.indexOf("include cssmodule")&&fs.exists(b+"/cssmodule.pug",function(a){a||fs.writeFile(b+"/cssmodule.pug","- css \x3d {}",function(a){if(a)throw a;})})};
wilokePlugin.prototype.writeScssFile=function(a,b,c){var d=this.opts,e=a.replace(/\.pug/g,".scss");a=c.match(/(?:\/\/.*demo: .*(\r\n|\r|\n))(mixin(.*)(?=(\()))/g);a=null!==a?a[0].replace(/\/\/-\s*.*(\r\n|\r|\n)mixin\s*/g,""):"";var f="/* //--- "+a+"\n--------------------------------------------------------------------------------*/\n",g=function(){-1!==c.indexOf("include cssmodule")&&-1!==c.indexOf("css.")&&(new Promise(function(a,b){fs.readFile(e,"utf-8",function(b,c){if(b)throw b;b=-1===c.indexOf(f)?
f+c:c;a([b,c])})})).then(function(a){var b=a[0];a=a[1];var g=remove_duplicates(c.match(/css\..\w*/g));g=$jscomp.makeIterator(g);for(var l=g.next();!l.done;l=g.next())l=l.value.replace(/.*\./g,""),-1===b.indexOf(l)&&(b+="\n// "+l+"\n."+l+" {\n\t\n}\n",d.styles.updateClass?a!==b&&fs.writeFile(e,b,function(a){if(a)throw a;}):a===f&&fs.writeFile(e,b,function(a){if(a)throw a;}))})};fs.exists(e,function(a){a?g():fs.writeFile(e,f,function(a){if(a)throw a;})})};
wilokePlugin.prototype.writeFileDemo=function(a,b,c){var d="//- Args:",e="",f=path.dirname(a)+"/demo.pug",g=c.match(/(?:\/\/.*demo: .*(\r\n|\r|\n))(mixin(.*)(?=(\()))/g);g=null!==g?g[0].replace(/\/\/-\s*.*(\r\n|\r|\n)mixin\s*/g,""):"";if(-1!==c.indexOf("args")&&-1!==c.search(/\/\/.*demo:\strue/g)){var k=a.replace(/\.pug/g,".scss");a=c.replace(/args.*modifier|if.*modifier/g,"").match(/(set\(\w+\D\s+\D\w+)/g);b=c.replace(/args.*modifier|if.*modifier/g,"").match(/(=|\(|&&|\|\|)\s*(args\.\w*)/g);c=[];
null!==a&&(a=remove_duplicates(a.toString().replace(/(set\(\w+)(,*\s('|"))/g," ").split(",")),c.push(a.join(",")));null!==b&&(a=remove_duplicates(b.toString().replace(/(=|\(|&&|\|\|)\s*(args\.)/g," ").split(",")),c.push(a.join(",")));d+=""+c.join(",");e='\x3cdiv class\x3d"wil-core-space"\x3e\x3cspan\x3e\x3c/span\x3e\x3cdiv class\x3d"wil-text-modifier"\x3e\x3cspan\x3edefault\x3c/span\x3e\x3c/div\x3e\x3c/div\x3e\n'+d+"\n+"+g+"({\n\t\n})\n";var h=function(){fs.exists(k,function(a){a&&fs.readFile(k,"utf-8",
function(a,b){if(a)throw a;a=-1!==b.indexOf("modifier")?b.match(/\/\/\s*modifier.*(\r\n|\r|\n).*/g).join("").match(/.*{/g):[1];a=$jscomp.makeIterator(a);for(b=a.next();!b.done;b=a.next())b=b.value,e+="string"===typeof b?'\x3cdiv class\x3d"wil-core-space"\x3e\x3cspan\x3e\x3c/span\x3e\x3cdiv class\x3d"wil-text-modifier"\x3e\x3cspan\x3emodifier: \''+b.replace(/\.|\s+\{/g,"")+"'\x3c/span\x3e\x3c/div\x3e\x3c/div\x3e\n"+d+"\n+"+g+"({\n\tmodifier: '"+b.replace(/\.|\s+\{/g,"")+"'\n})\n":"",fs.readFile(f,
"utf-8",function(a,b){if(a)throw a;b!==e&&fs.writeFile(f,e,function(a){if(a)throw a;})})})})};fs.exists(f,function(a){a?h():fs.writeFile(f,"",function(a){if(a)throw a;})})}};wilokePlugin.prototype.writeFiles=function(a,b,c){var d=a+"/"+b+".pug";fs.exists(d,function(e){e?fs.readFile(d,"utf-8",function(d,g){if(d)throw d;g!==c&&fs.writeFile(a+"/"+b+".pug",c,function(a){if(a)throw a;})}):fs.writeFile(a+"/"+b+".pug","",function(a){if(a)throw a;})})};
wilokePlugin.prototype.checkIncludeComp=function(){var a=this.opts.appConfig,b=a.folders.path+"/"+a.folders.content+"/"+activate+"/"+a.entry.path+"/pug/includes/authorFolder",c;for(c in this.includeComp)if("undefined"!==typeof this.includeComp[c][0]){var d="include------"+this.includeComp[c].join("\ninclude------");d=d.replace(new RegExp("------.*"+a.folders.path,"g")," ");this.writeFiles(b,c,d)}};
wilokePlugin.prototype.checkIncludeDemo=function(){var a=this.opts.appConfig;a=a.folders.path+"/"+a.folders.content+"/"+activate+"/"+a.entry.path+"/pug/docs-includes/authorFolder";for(var b in this.includeDemo)if("undefined"!==typeof this.includeDemo[b][0]){var c=this.includeDemo[b].join("\n");this.writeFiles(a,b,c)}};
wilokePlugin.prototype.writefileFlag=function(a){a=this.opts.appConfig;var b=a.folders.path+"/"+a.folders.content+"/"+activate+"/"+a.entry.path;a=a.folders.path+"/"+a.folders.content+"/"+activate+"/config.js";fs.watch("app.config.js",function(){fs.writeFile(b+"/pug/flag.pug","",function(a){if(a)throw a;})});fs.watch(a,function(){fs.writeFile(b+"/pug/flag.pug","",function(a){if(a)throw a;})})};
wilokePlugin.prototype.delFileAuthor=function(a){var b=a+"/authorFolder";fs.readdir(b,function(a,d){if(a)throw a;a={};d=$jscomp.makeIterator(d);for(var c=d.next();!c.done;a={file:a.file},c=d.next())a.file=c.value,fs.exists(b+"/"+a.file,function(a){return function(c){c&&fs.unlink(b+"/"+a.file,function(a){if(a)throw a;})}}(a))})};
wilokePlugin.prototype.beforeBegin=function(){var a=this.opts,b=a.appConfig;b=b.folders.path+"/"+b.folders.content+"/"+activate+"/"+b.entry.path;var c=b+"/pug/includes/includes.pug",d=b+"/pug/docs-includes/docs-includes.pug";(new Promise(function(a,b){fs.writeFile(c,"",function(a){if(a)throw a;});fs.writeFile(d,"",function(a){if(a)throw a;});a("OK");b("Err")})).then(function(){for(var b="",g="mixin include(file)",e=$jscomp.makeIterator(a.authorTree),h=e.next();!h.done;h=e.next())h=decode(h.value).replace(/.*(\\|\/)/g,
""),b+="include authorFolder/"+h+".pug\n",g+="\n\tinclude authorFolder/"+h+".pug",fs.readFile(c,"utf-8",function(a,d){if(a)throw a;""===d&&fs.writeFile(c,b,function(a){if(a)throw a;})}),fs.readFile(d,"utf-8",function(a,b){if(a)throw a;""===b&&fs.writeFile(d,g,function(a){if(a)throw a;})})}).catch(function(a){return console.log(a)});b=$jscomp.makeIterator(a.authorTree);for(var e=b.next();!e.done;e=b.next())e=decode(e.value),watch(e,{recursive:!0}).on("change",function(a,b){fs.exists(b,function(a){if(a&&
-1!==b.indexOf("cssmodule.pug")){var c=fs.readFileSync(b,"utf-8");c=c.replace(/:"/g,':".');c=c.match(/{.*}/g)[0];c=c.replace(/"}/g,'","":""}');c=c.replace(/","/g,'",\n"');c=c.replace(/\s\w.*",\n/g,'",');c=c.replace(/",\n"/g,'","');var d=glob.sync(path.dirname(b)+"/*.js")[0];fs.existsSync(d)&&fs.readFile(d,"utf-8",function(a,b){-1!==b.search(/this\.css\s+=/g)?(a=b.match(/this\.css.*([\s\S]*?)"":(\s+|)""(\n|).*/g)[0].replace(/this.css.*=\s/g,""),a=a.replace(/","/g,'",\n"'),a=a.replace(/\s\w.*",\n/g,
'",'),a=a.replace(/",\n"/g,'","'),a!==c&&fs.writeFile(d,b.replace(/this\.css.*([\s\S]*?)"":(\s+|)""(\n|).*/g,"this.css \x3d "+c+";"),function(a){if(a)throw a;})):-1!==b.search(/const\s+css\s+=/g)&&(a=b.match(/const\s+css.*([\s\S]*?)"":(\s+|)""(\n|).*/g)[0].replace(/const\s+css\s+=\s/g,""),a=a.replace(/","/g,'",\n"'),a=a.replace(/\s\w.*",\n/g,'",'),a=a.replace(/",\n"/g,'","'),a!==c&&fs.writeFile(d,b.replace(/const\s+css.*([\s\S]*?)"":(\s+|)""(\n|).*/g,"const css \x3d "+c+";"),function(a){if(a)throw a;
}))})}})})};wilokePlugin.prototype.emit=function(a){var b=this;a.plugin("emit",function(a,d){isDev&&b.checkIncludeDemo();d()})};
wilokePlugin.prototype.cssModuleForJs=function(a){var b=this;if(this.opts.cssModuleForJs)try{-1!==a.indexOf("_pattern")&&-1!==a.indexOf(".js")&&fs.readFile(a,"utf-8",function(c,d){if(c)throw c;var e=path.dirname(a)+"/cssmodule.pug";if(null!==d.match(/^.*/g)){var f=b.jsBasic(d.match(/^.*/g)[0]);fs.exists(e,function(b){b&&(b=fs.readFileSync(e,"utf-8"),b=b.replace(/:"/g,':".'),b=b.match(/{.*}/g)[0],b=b.replace(/"}/g,'","":""}'),b=b.replace(/","/g,'",\n"'),b=b.replace(/\s\w.*",\n/g,'",'),b=b.replace(/",\n"/g,
'","'),f=f.replace(/jsBasicPattern/g,camelCase(a.replace(/.*(\/|\\)|\.js/g,""))),f=f.replace(/replaceCssModule/g,b),""===d.replace(/^.*|\n/g,"")?fs.writeFileSync(a,f):-1!==d.indexOf("replaceCssModule")&&fs.writeFileSync(a,d.replace(/replaceCssModule/g,b)))})}})}catch(c){console.log(c.message)}};
wilokePlugin.prototype.invalid=function(a){var b=this,c=this.opts,d=c.appConfig;a.plugin("invalid",function(a,f){f=$jscomp.makeIterator(c.authorTree);for(var e=f.next();!e.done;e=f.next())e=e.value,-1!==decode(e).search(new RegExp("_pattern(\\/|\\\\)"+rqPattern,"g"))&&(e=decode(e),b.watchFolderComp(e),b.checkPugFile(e),b.writefileFlag(e));f=$jscomp.makeIterator(c.authorTree);for(e=f.next();!e.done;e=f.next()){var k=decode(e.value);e=k.replace(/.*(\\|\/)/g,"");var h=glob.sync(k+"/**/demo.pug"),m=[];
b.includeComp[e]=b.filePugCompAndData(k);k=$jscomp.makeIterator(h);for(h=k.next();!h.done;h=k.next())h=h.value,m.push(('if (file \x3d\x3d\x3d "------'+h+'")\n\tinclude ------'+h).replace(new RegExp("------.*"+d.folders.path,"g"),"")),b.includeDemo[e]=m}isDev&&(b.checkIncludeComp(),b.createBasicPage());b.cssModuleForJs(a)})};wilokePlugin.prototype.apply=function(a){this.beforeBegin();this.invalid(a);this.emit(a)};
var encode=function(a){return(new Buffer(a)).toString("base64")},decode=function(a){return(new Buffer(a+"\x3d","base64")).toString("ascii")},remove_duplicates=function(a){for(var b={},c=[],d=0,e=a.length;d<e;d++)b[a[d]]=!0;for(var f in b)c.push(f);return c},capitalize=function(a){return a.charAt(0).toUpperCase()+a.toLowerCase().slice(1)},camelCase=function(a){a=a.toLowerCase().replace(/[^A-Za-z0-9]/g," ").split(" ").reduce(function(a,c){return a+capitalize(c.toLowerCase())});return a.charAt(0).toLowerCase()+
a.slice(1)};module.exports=wilokePlugin;